### ISSUE TITLE
Encode numerical constants

### ISSUE THREAD

**Issue by tobiaswjohn** [remaro-network/dlToPlanning#14]
Implement an automatic generation of comparing the extracted constants + constants from the planning file. Use similar approach as in [this problem file](https://github.com/AI-Planning/unsolve-ipc-2016/blob/master/domains/FINAL/over-nomystery/prob01.pddl).

Consider:
 - how to extract numbers from planning file (how are they encoded?)
 - what predicate to use for the comparison
 - which types of numbers to parse

**Comment by tobiaswjohn** [comment]
extracting the relation for decimal values in the ontology is now solved and the "leq", i.e., lower of equal, relation can be used in the action descriptions to compare two values. 
Corresponding commit: 44e8bafeeef18d86d4e851ea841bf1b128005be2.

What is still missing: checking the problem file for existing numerical values and adding comparison operations for them.

**Comment by tobiaswjohn** [comment]
Solved with commit 68f3fb5be37fb68d5c3ea69500cbe6670dba5fa2.
Numbers in PDDL problem need to be of type `number` to be considered for parsing. and the numbers have the following format: `<number>_<type>`, e.g. `3.15_decimal`
So far, the implementation can parse numbers of type `decimal`. Please open new issue, if support for more types of numbers is desired.

**Comment by tobiaswjohn** [comment]
As of commit b1585ac2225432d2e475ec2b55dd6b443c5251ee, the comparison operators for numbers are now `lessThan` and `equalsTo`

**Comment by Rezenders** [comment]
Hi @tobiaswjohn,

I am not sure if I am doing something wrong, but I cannot replicate this. The `lessThan` and `equalsTo` predicates are not being generated.
Check: https://github.com/remaro-network/dlToPlanning/blob/suave/examples/suave/suave_problem_created.pddl

**Comment by tobiaswjohn** [comment]
The issue is probably a lack of documentation from my side... Do you run the program with the argument `--add-num-comparisons`?
Also: You have some objects of type "number" in your problem. You probably want to use "owl-number". I changed this, because I realized that "number" is already defined for different purposes in PDDL (although noone seems to use it).

**Comment by Rezenders** [comment]
It worked with the `--add-num-comparisons`, thanks.
Ok, I will use only `owl-number`
