### ISSUE TITLE
introdcue "number" type to domain, if required

### ISSUE THREAD

**Issue by tobiaswjohn** [remaro-network/dlToPlanning#16]
if the type "number" does not exist in domain but number are added to problem file --> add the type to the domain.

**Comment by tobiaswjohn** [comment]
should be "owl-number"

**Comment by Rezenders** [comment]
I guess this issue can be closed, right?

**Comment by tobiaswjohn** [comment]
The same issue still remains for `owl-number`, so I want to keep this open.

**Comment by tobiaswjohn** [comment]
should be solved now. If pddl types are required (e.g. `owl-number` or types contained in ontology), they are added to the pddl domain if they are not defined.
