### ISSUE TITLE
Add types where possible

### ISSUE THREAD

**Issue by Rezenders** [remaro-network/dlToPlanning#20]
Running the planner with the current pddl formulation for SUAVE takes around 0.5 seconds. I believe this can be improved with a better typing system by adding specialized types for the objects, e.g., `fd_recover_thrusters - function_design` and so on.

Also, PlanSys is taking very long to solve all the derived predicates (around 30 seconds) due to my poor implementation of supporting existential preconditions and derived predicates. I believe this could be greatly improved if objects and constants had more specialized types that are not subtypes of each other, i.e., part of another type hierarchy. 

@tobiaswjohn do you think you could do such modifications the owl->pddl tool?

**Comment by tobiaswjohn** [comment]
I think there are two views on this issue:
 1. technically, it is not a big problem to introduce such types.  BUT
 2. this results in not interpreting the axioms in the ontology as usual, i.e. we use OWL as a modelling language without using the OWL interpretation. I've seen this a couple of times and I think it makes it really hard for others to understand what we do. 

I propose to focus on removing the unnecessary derived predicates (i.e. most of them) first (see issue #19) and see what the difference is before adding more types is a non-owl-conformant way.

**Comment by tobiaswjohn** [comment]
I propose, we add a new class `PddlType` that contains all types that are relevant for us and that are used in the planning domain. A type is an individual, that has a data relation `pddlName` to a string, which represents the name of the type in PDDL. Additionally, we add a relation `hasPddlType` to the ontology. As the name hints, this points to the type in pddl of an individual. The whole ontology representation would look something like this:
![pddlTypes drawio](https://github.com/user-attachments/assets/97d0db31-ec75-4e00-a8dc-6a28860236eb)

There is some programming work involved to get this working. I will see, if I can manage to do this till the end of the week.
