### ISSUE TITLE
Class as predicate or type?

### ISSUE THREAD

**Issue by Rezenders** [remaro-network/dlToPlanning#5]
Hi @tobiaswjohn,

Is there a specific reason why you transform OWL Classes into PDDL predicates?
In my view, it would make more sense to have the OWL Classes converted to PDDL types, as they are not a relationship. Keeping only the data and object properties as predicates. What do you think?

**Comment by tobiaswjohn** [comment]
Yes, transforming OWL classes to predicates is done on purpose and we could not do this with types. 
The main reason: the class of an individual in the ontology can change over time (similar how the predicate can switch between being true or false over time) but the type of an object in PDDL remains always the same. I.e., the membership in an OWL class is not a type.
Another reason that is more technical: although I am not too familiar with types in PDDL, I assume that things like types being sub-types of several types or objects having multiple types might be an issue, which is no problem for OWL classes.

**Comment by tobiaswjohn** [comment]
yes, something like this.
