### ISSUE TITLE
Convert OWL instances to PDDL problem formulation

### ISSUE THREAD

**Issue by Rezenders** [remaro-network/dlToPlanning#6]
@tobiaswjohn I think it would also be useful to be able to convert the data instances from OWL into a PDDL problem definition. What do you think?

**Comment by tobiaswjohn** [comment]
I am not sure, what exactly you mean. Can you provide an example of a "data instance". In general, all relations should be converted, i.e. the ABox should become part of the PDDL problem (but this is not implemented yet). Is that what you mean?

**Comment by Rezenders** [comment]
> i.e. the ABox should become part of the PDDL problem (but this is not implemented yet). Is that what you mean?

Yes, that is what I mean :)

**Comment by tobiaswjohn** [comment]
should be solved with 7362dd0d87c65a0018b1b1788ad4644f4c9ac750

**Comment by Rezenders** [comment]
What about data properties? Such as `hasValue`, `qa_comparison_operator`, `c_status` etc?

**Comment by tobiaswjohn** [comment]
I wasn't aware that they also occur in our examples in the ontology. At least in the example, this was not the case (as far as I know...) 
But I can add support for them. Should not be a big issue...

**Comment by tobiaswjohn** [comment]
I just checked. It should already be implemented, but there seems to be a bug somewhere... I opend #13  as this is a separate issue.
